### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4ir-doc2query#4]
```
[tong.guo@gpu-4 dl4ir-doc2query-master]$ /data4/tong.guo/Py36/bin/python3  ./OpenNMT-py/preprocess.py   -train_src ${DATA_DIR}/opennmt_format/src-train.txt   -train_tgt ${DATA_DIR}/opennmt_format/tgt-train.txt   -valid_src ${DATA_DIR}/opennmt_format/src-dev.txt   -valid_tgt ${DATA_DIR}/opennmt_format/tgt-dev.txt   -save_data ${DATA_DIR}/opennmt_format/preprocessed   -src_seq_length 10000   -tgt_seq_length 10000   -src_seq_length_trunc 400   -tgt_seq_length_trunc 100   -dynamic_dict   -share_vocab   -src_vocab_size 32000   -tgt_vocab_size 32000   -shard_size 100000
[2019-07-05 16:19:16,352 INFO] Extracting features...
[2019-07-05 16:19:16,352 INFO]  * number of source features: 0.
[2019-07-05 16:19:16,352 INFO]  * number of target features: 0.
[2019-07-05 16:19:16,352 INFO] Building `Fields` object...
[2019-07-05 16:19:16,352 INFO] Building & saving training data...
[2019-07-05 16:19:16,352 INFO] Reading source and target files: ./data/opennmt_format/src-train.txt ./data/opennmt_format/tgt-train.txt.
[2019-07-05 16:19:16,439 INFO] Building shard 0.
[2019-07-05 16:19:35,996 INFO]  * saving 0th train data shard to ./data/opennmt_format/preprocessed.train.0.pt.
[2019-07-05 16:20:19,033 INFO] Building shard 1.
[2019-07-05 16:20:38,667 INFO]  * saving 1th train data shard to ./data/opennmt_format/preprocessed.train.1.pt.
[2019-07-05 16:21:20,578 INFO] Building shard 2.
[2019-07-05 16:21:38,967 INFO]  * saving 2th train data shard to ./data/opennmt_format/preprocessed.train.2.pt.
[2019-07-05 16:22:18,861 INFO] Building shard 3.
[2019-07-05 16:22:38,026 INFO]  * saving 3th train data shard to ./data/opennmt_format/preprocessed.train.3.pt.
[2019-07-05 16:23:17,526 INFO] Building shard 4.
[2019-07-05 16:23:36,450 INFO]  * saving 4th train data shard to ./data/opennmt_format/preprocessed.train.4.pt.
[2019-07-05 16:24:14,980 INFO] Building shard 5.
[2019-07-05 16:24:21,203 INFO]  * saving 5th train data shard to ./data/opennmt_format/preprocessed.train.5.pt.
[2019-07-05 16:24:33,794 INFO] Building & saving validation data...
[2019-07-05 16:24:33,794 INFO] Reading source and target files: ./data/opennmt_format/src-dev.txt ./data/opennmt_format/tgt-dev.txt.
[2019-07-05 16:24:33,798 INFO] Building shard 0.
[2019-07-05 16:24:35,017 INFO]  * saving 0th valid data shard to ./data/opennmt_format/preprocessed.valid.0.pt.
[2019-07-05 16:24:37,548 INFO] Building & saving vocabulary...
[2019-07-05 16:24:56,466 INFO]  * reloading ./data/opennmt_format/preprocessed.train.0.pt.
[2019-07-05 16:25:20,221 INFO]  * reloading ./data/opennmt_format/preprocessed.train.1.pt.
[2019-07-05 16:25:43,888 INFO]  * reloading ./data/opennmt_format/preprocessed.train.2.pt.
[2019-07-05 16:26:07,105 INFO]  * reloading ./data/opennmt_format/preprocessed.train.3.pt.
[2019-07-05 16:26:30,643 INFO]  * reloading ./data/opennmt_format/preprocessed.train.4.pt.
[2019-07-05 16:26:41,342 INFO]  * reloading ./data/opennmt_format/preprocessed.train.5.pt.
[2019-07-05 16:26:42,716 INFO]  * tgt vocab size: 32004.
[2019-07-05 16:26:45,684 INFO]  * src vocab size: 32002.
[2019-07-05 16:26:45,684 INFO]  * merging src and tgt vocab...
[2019-07-05 16:26:50,727 INFO]  * merged vocab size: 32004.
Traceback (most recent call last):
  File "./OpenNMT-py/preprocess.py", line 155, in <module>
    main(opt)
  File "./OpenNMT-py/preprocess.py", line 140, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "./OpenNMT-py/preprocess.py", line 91, in build_save_vocab
    torch.save(fields, vocab_path)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 143, in _with_file_like
    return body(f)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 291, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function Field.<lambda> at 0x7ffaad122d90>: attribute lookup Field.<lambda> on torchtext.data.field failed
```

torch                       1.0.0            
torchfile                   0.1.0            
torchtext                   0.3.1            
torchvision                 0.2.1  

OpenNMT-py            0.8.2

python3.6

Thank you!
@rodrigonogueira4

**Comment by guotong1988** [comment]
I try torch 1.1.0.
Not work.

**Comment by guotong1988** [comment]
```
Traceback (most recent call last):
  File "./OpenNMT-py/preprocess.py", line 218, in <module>
    main(opt)
  File "./OpenNMT-py/preprocess.py", line 199, in main
    'train', fields, src_reader, tgt_reader, opt)
  File "./OpenNMT-py/preprocess.py", line 142, in build_save_dataset
    torch.save(fields, vocab_path)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/torch/serialization.py", line 297, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function Field.<lambda> at 0x7fa81168e2f0>: attribute lookup Field.<lambda> on torchtext.data.field failed
```

torch 1.1.0
OpenNMT-py 0.9.1

Not work.

**Comment by guotong1988** [comment]
https://github.com/OpenNMT/OpenNMT-py/issues/1165
